#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

curl -LsSf https://astral.sh/uv/0.11.6/install.sh | sh
uv python install
uv run pre-commit install

ln -s /workspaces/ha-sma-ev-charger/custom_components /workspaces/ha-sma-ev-charger/config/custom_components
