name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install pre-commit dependencies
      run: |
        pre-commit install-hooks
    - name: Run black
      run: |
        pre-commit run black --all-files --show-diff-on-failure
    - name: Run ruff
      run: |
        pre-commit run ruff --all-files --show-diff-on-failure
