name: pytest

on:
  push:
    branches: [feat/tests]
  pull_request:

jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        core-version: ["2024.1.5", "dev"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Install Home Assistant
        uses: ./.github/workflows/install_dependencies
        with:
          python-version: ${{ matrix.python-version }}
          core-version: ${{ matrix.core-version }}

      - name: Link custom_components/smaev
        run: |
          cd core

          # Link smaev tests
          cd tests/components/
          ln -fs ../../../tests smaev
          cd -

      - name: Run pytest
        timeout-minutes: 60
        run: |
          export PYTHONPATH=${PYTHONPATH}:${PWD}
          cd core
          python3 -X dev -m pytest \
            -vvv \
            -qq \
            --timeout=9 \
            --durations=10 \
            --cov="custom_components.smaev" \
            --cov-report=xml \
            -o console_output_style=count \
            -p no:sugar \
            tests/components/smaev
        env:
          HA_CLONE: true
